services:
  - type: web
    name: pepper-disease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
